Test Backend Round 1

diff --git a/.github/workflows/deploy_backend.yml b/.github/workflows/deploy_backend.yml
--- a/.github/workflows/deploy_backend.yml
+++ b/.github/workflows/deploy_backend.yml
@@ -65,10 +65,10 @@ jobs:
           
             - name: Calculate Docker Compose hash
               id: hash
-              run: echo "::set-output name=compose_hash::$(sha256sum core_backend/deployment/docker-compose.yml | awk '{print $1}')"
+              run: echo "compose_hash=$(sha256sum core_backend/deployment/docker-compose.yml | awk '{print $1}')" >> $GITHUB_OUTPUT
         
             - name: Cache Docker Compose hash
-              uses: actions/cache@v2
+              uses: actions/cache@v3
               with:
                 path: |
                   ./.compose_hash
@@ -78,10 +78,10 @@ jobs:
               id: check_changes
               run: |
                 if [ -f ./.compose_hash ] && [ "$(< ./.compose_hash)" == "${{ steps.hash.outputs.compose_hash }}" ]; then
-                  echo "::set-output name=changed::false"
+                  echo "changed=false" >> $GITHUB_OUTPUT
                 else
                   echo "${{ steps.hash.outputs.compose_hash }}" > ./.compose_hash
-                  echo "::set-output name=changed::true"
+                  echo "changed=true" >> $GITHUB_OUTPUT
                 fi
             - name: Install the ECS CLI
               if: steps.check_changes.outputs.changed == 'true'
@@ -107,39 +107,39 @@ jobs:
                 DOMAIN: ${{ env.DOMAIN }}
             # We need this since deploy task definition action needs the task definition in json format
             
-            - name: Task definition download
-              id: download-task-def
-              env:
-                ecs_task_def_name: backend-task
-              run: |
-                aws ecs describe-task-definition --task-definition "$ecs_task_def_name" --query taskDefinition > task-definition.json
-                echo $(cat task-definition.json | jq 'del(
-                  .taskDefinitionArn,
-                  .requiresAttributes,
-                  .compatibilities,
-                  .revision,
-                  .status,
-                  .registeredAt,
-                  .registeredBy
-                )') > task-definition.json
-                echo "task-def=task-definition.json" >> $GITHUB_OUTPUT
+            # - name: Task definition download
+            #   id: download-task-def
+            #   env:
+            #     ecs_task_def_name: backend-task
+            #   run: |
+            #     aws ecs describe-task-definition --task-definition "$ecs_task_def_name" --query taskDefinition > task-definition.json
+            #     echo $(cat task-definition.json | jq 'del(
+            #       .taskDefinitionArn,
+            #       .requiresAttributes,
+            #       .compatibilities,
+            #       .revision,
+            #       .status,
+            #       .registeredAt,
+            #       .registeredBy
+            #     )') > task-definition.json
+            #     echo "task-def=task-definition.json" >> $GITHUB_OUTPUT
             
-            - name: Deploy Amazon ECS task definition
-              id: ecs-deploy
-              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
-              with:
-                task-definition: ${{ steps.download-task-def.outputs.task-def }}
-                service: backend-service
-                cluster: ${{ env.CLUSTER_NAME }} 
-                wait-for-service-stability: true
-            - name: Check if deployment was successful
-              id: check-deployment
-              run: |
-                  RUNNING_TASKS=$(aws ecs describe-services --cluster ${{ env.CLUSTER_NAME }} --services backend-service --query services[0].deployments[0].runningCount | jq -r ".")
+            # - name: Deploy Amazon ECS task definition
+            #   id: ecs-deploy
+            #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+            #   with:
+            #     task-definition: ${{ steps.download-task-def.outputs.task-def }}
+            #     service: backend-service
+            #     cluster: ${{ env.CLUSTER_NAME }} 
+            #     wait-for-service-stability: true
+            # - name: Check if deployment was successful
+            #   id: check-deployment
+            #   run: |
+            #       RUNNING_TASKS=$(aws ecs describe-services --cluster ${{ env.CLUSTER_NAME }} --services backend-service --query services[0].deployments[0].runningCount | jq -r ".")
                   
-                  if [ "$RUNNING_TASKS" -eq "0" ]; then
-                    echo "Deployment failed."
-                    exit 1
-                  fi
+            #       if [ "$RUNNING_TASKS" -eq "0" ]; then
+            #         echo "Deployment failed."
+            #         exit 1
+            #       fi
                   
                 
