Testing Backend URL

diff --git a/.github/workflows/deploy_frontend.yml b/.github/workflows/deploy_frontend.yml
--- a/.github/workflows/deploy_frontend.yml
+++ b/.github/workflows/deploy_frontend.yml
@@ -61,14 +61,38 @@ jobs:
                 push: true
                 tags: ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
                 build-args: |
-                  NAME=${{env.NEXT_PUBLIC_BACKEND_URL}}
+                  NEXT_PUBLIC_BACKEND_URL=${{env.NEXT_PUBLIC_BACKEND_URL}}
+          # This makes sure that the Docker Compose file is cached between builds and only changes to the file will trigger creation of task definition
+          # This will reduce the number of task definitions created and will speed up the deployment process
+          # A drawback of this approach is that if you change the variables used in the Docker Compose, the task definition will not be updated
+            - name: Calculate Docker Compose hash
+              id: hash
+              run: echo "compose_hash=$(sha256sum admin_app/deployment/docker-compose.yml | awk '{print $1}')" >> $GITHUB_OUTPUT
+    
+            - name: Cache Docker Compose hash
+              uses: actions/cache@v3
+              with:
+                path: |
+                  ./.compose_hash
+                key: ${{ steps.hash.outputs.compose_hash }}
                 
+            - name: Check for changes in Docker Compose
+              id: check_changes
+              run: |
+                if [ -f ./.compose_hash ] && [ "$(< ./.compose_hash)" == "${{ steps.hash.outputs.compose_hash }}" ]; then
+                  echo "changed=false" >> $GITHUB_OUTPUT
+                else
+                  echo "${{ steps.hash.outputs.compose_hash }}" > ./.compose_hash
+                  echo "changed=true" >> $GITHUB_OUTPUT
+                fi     
 
             - name: Install the ECS CLI
+              if: steps.check_changes.outputs.changed == 'true'
               run: |
                 sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
                 sudo chmod +x /usr/local/bin/ecs-cli
             - name: Create Task Definition
+              if: steps.check_changes.outputs.changed == 'true'
               id: create-task-def
               run: |
                 ecs-cli configure --cluster ${{ env.CLUSTER_NAME }} \
@@ -87,33 +111,35 @@ jobs:
                 ecs_task_def_name: admin-app-task
               run: |
                 aws ecs describe-task-definition --task-definition "$ecs_task_def_name" --query taskDefinition > task-definition.json
+                echo $(cat task-definition.json | jq 'del(
+                  .taskDefinitionArn,
+                  .requiresAttributes,
+                  .compatibilities,
+                  .revision,
+                  .status,
+                  .registeredAt,
+                  .registeredBy
+                )') > task-definition.json
+                echo "task-def=task-definition.json" >> $GITHUB_OUTPUT
             
-            - name: Fill in the new image ID in the Amazon ECS task definition
-              id: task-def
-              uses: aws-actions/amazon-ecs-render-task-definition@v1
-              with:
-                task-definition: task-definition.json
-                container-name: admin-app-container
-                image: ${{ fromJson(steps.build-image.outputs.metadata)['image.name'] }}
+           
             
             - name: Deploy Amazon ECS task definition
               id: ecs-deploy
               uses: aws-actions/amazon-ecs-deploy-task-definition@v1
               with:
-                task-definition: ${{ steps.task-def.outputs.task-definition }}
+                task-definition: ${{ steps.download-task-def.outputs.task-def }}
                 service: admin-app-service
                 cluster: ${{ env.CLUSTER_NAME }} 
                 wait-for-service-stability: true
             - name: Check if deployment was successful
               id: check-deployment
               run: |
-                  CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ env.CLUSTER_NAME }} --services admin-app-service --query services[0].deployments[0].taskDefinition | jq -r ".")
-                  NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
-                  echo "Current task arn: $CURRENT_TASK_DEF_ARN"
-                  echo "New task arn: $NEW_TASK_DEF_ARN"
-                  if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
-                    echo "Deployment failed."
-                    exit 1
-                  fi
+                RUNNING_TASKS=$(aws ecs describe-services --cluster ${{ env.CLUSTER_NAME }} --services nginx-service --query services[0].deployments[0].runningCount | jq -r ".")
+                    
+                if [ "$RUNNING_TASKS" -eq "0" ]; then
+                  echo "Deployment failed."
+                  exit 1
+                fi
                 
                 
